import logging
from typing import Optional
from fastapi import APIRouter, Request, Response, HTTPException, status
from fastapi.responses import HTMLResponse

from app.services.unsubscribe_service import unsubscribe_service

logger = logging.getLogger("email_service")
router = APIRouter(tags=["Unsubscribe"])


@router.get(
    "/unsubscribe",
    response_class=HTMLResponse,
    summary="One-Click Unsubscribe",
    description=(
        "Verifies the HMAC-signed unsubscribe token from the email footer link, "
        "adds the email to the suppression list, and returns a confirmation HTML page."
    ),
)
def handle_unsubscribe(token: str, request: Request):
    """
    Processes a one-click unsubscribe request.
    Token is generated by UnsubscribeService and embedded in every marketing email footer.
    """
    try:
        email = unsubscribe_service.verify_token(token)
    except ValueError as e:
        logger.warning(f"Unsubscribe: invalid token received — {e}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Invalid or expired unsubscribe link: {e}",
        )

    newly_suppressed = unsubscribe_service.unsubscribe_email(email, reason="unsubscribed")
    logger.info(f"Unsubscribe: {email} processed (new_suppression={newly_suppressed})")

    if newly_suppressed:
        html = _render_success_page(email)
    else:
        html = _render_already_page(email)

    return HTMLResponse(content=html, status_code=200)


@router.post(
    "/unsubscribe",
    status_code=status.HTTP_200_OK,
    summary="List-Unsubscribe-Post (RFC 8058)",
    description=(
        "Handles the machine-initiated List-Unsubscribe-Post header used by Gmail/Yahoo. "
        "Email clients send a POST to this endpoint when the user clicks 'Unsubscribe' "
        "from the email client's built-in UI. No token required — email passed in body."
    ),
)
async def list_unsubscribe_post(request: Request):
    """
    RFC 8058 compliant List-Unsubscribe-Post handler.
    Gmail and Yahoo send a POST with `List-Unsubscribe=One-Click` in the body.
    """
    try:
        body = await request.form()
        email = str(body.get("email", ""))
        if not email:
            # Some clients send it as JSON
            json_body = await request.json()
            email = json_body.get("email", "")
    except Exception:
        email = ""

    if email:
        unsubscribe_service.unsubscribe_email(email, reason="list-unsubscribe-post")
        logger.info(f"List-Unsubscribe-Post: {email} suppressed via RFC 8058.")

    # RFC 8058: Always return 200 OK
    return {"status": "ok"}


# ---------------------------------------------------------------------------
# HTML pages (inline — no template file needed)
# ---------------------------------------------------------------------------

def _render_success_page(email: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Unsubscribed — SyncRivo</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            background: #f8fafc; display: flex; align-items: center;
            justify-content: center; min-height: 100vh; }}
    .card {{ background: #fff; border-radius: 16px; padding: 48px 40px;
             max-width: 480px; text-align: center; box-shadow: 0 4px 24px rgba(0,0,0,.08); }}
    .icon {{ font-size: 56px; margin-bottom: 20px; }}
    h1 {{ font-size: 24px; color: #1e293b; margin-bottom: 12px; }}
    p {{ color: #64748b; line-height: 1.6; font-size: 15px; }}
    .email {{ display: inline-block; margin: 12px 0; padding: 6px 16px;
              background: #f1f5f9; border-radius: 6px; font-weight: 600;
              color: #334155; font-size: 14px; }}
    .note {{ margin-top: 24px; font-size: 13px; color: #94a3b8; }}
  </style>
</head>
<body>
  <div class="card">
    <div class="icon">✅</div>
    <h1>You've been unsubscribed</h1>
    <p>The email address</p>
    <div class="email">{email}</div>
    <p>has been removed from our mailing list.</p>
    <p>You will no longer receive marketing emails from SyncRivo.</p>
    <p class="note">Transactional emails (demo confirmations, account notices) may still be sent as required.</p>
  </div>
</body>
</html>"""


def _render_already_page(email: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Already Unsubscribed — SyncRivo</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            background: #f8fafc; display: flex; align-items: center;
            justify-content: center; min-height: 100vh; }}
    .card {{ background: #fff; border-radius: 16px; padding: 48px 40px;
             max-width: 480px; text-align: center; box-shadow: 0 4px 24px rgba(0,0,0,.08); }}
    .icon {{ font-size: 56px; margin-bottom: 20px; }}
    h1 {{ font-size: 24px; color: #1e293b; margin-bottom: 12px; }}
    p {{ color: #64748b; line-height: 1.6; font-size: 15px; }}
    .email {{ display: inline-block; margin: 12px 0; padding: 6px 16px;
              background: #f1f5f9; border-radius: 6px; font-weight: 600;
              color: #334155; font-size: 14px; }}
  </style>
</head>
<body>
  <div class="card">
    <div class="icon">ℹ️</div>
    <h1>Already unsubscribed</h1>
    <p>The email address</p>
    <div class="email">{email}</div>
    <p>is already on our suppression list. You will not receive any marketing emails from SyncRivo.</p>
  </div>
</body>
</html>"""
